/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pro1p1_víctorromero;

import javax.swing.JOptionPane;
import static pro1p1_víctorromero.Conversiones.aleatorio;

/**
 *
 * @author Fam. Romero
 */
public class Recursion extends javax.swing.JFrame {

    /**
     * Creates new form Recursion
     */
    public Recursion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Personas = new javax.swing.JButton();
        Tesla = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Tesla1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Staccato222 BT", 0, 80)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<Recursión>");

        jLabel6.setFont(new java.awt.Font("Staccato222 BT", 0, 60)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Proyect");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(91, 91, 91))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        Personas.setFont(new java.awt.Font("Neo Sans", 0, 60)); // NOI18N
        Personas.setText("Conversiones");
        Personas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PersonasMouseClicked(evt);
            }
        });
        Personas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonasActionPerformed(evt);
            }
        });

        Tesla.setFont(new java.awt.Font("Neo Sans", 0, 40)); // NOI18N
        Tesla.setText("Menu");
        Tesla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TeslaMouseClicked(evt);
            }
        });
        Tesla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeslaActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p1_víctorromero/Logo.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        Tesla1.setFont(new java.awt.Font("Neo Sans", 0, 60)); // NOI18N
        Tesla1.setText("Matrices");
        Tesla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tesla1MouseClicked(evt);
            }
        });
        Tesla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tesla1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Tesla, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Tesla1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Personas, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Personas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Tesla1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(Tesla, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PersonasMouseClicked
        new Conversiones().setVisible(true);
        dispose();
    }//GEN-LAST:event_PersonasMouseClicked

    private void PersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PersonasActionPerformed

    private void TeslaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeslaMouseClicked
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_TeslaMouseClicked

    private void TeslaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeslaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeslaActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

    }//GEN-LAST:event_jLabel7MouseClicked

    private void Tesla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tesla1MouseClicked
        int fila = Integer.parseInt(JOptionPane.showInputDialog(this, ">> Ingrese el numero de Filas:"));
        int columna = Integer.parseInt(JOptionPane.showInputDialog(this, ">> Ingrese el numero de Columnas:"));

        int[][] matrix = new int[fila][columna];
        int[][] matrix2 = lectura(matrix, fila, columna);
        int[][] matrix3 = lectura(matrix, fila, columna);
        String answer = "";
        String answer2 = "";
        JOptionPane.showMessageDialog(this, "La Matriz es: \n" + Print(matrix2, fila - 1, columna - 1, answer));
        
        int filaEsp = Integer.parseInt(JOptionPane.showInputDialog(this, ">> Ingrese el numero de Filas:"));
        int columnaEsp = Integer.parseInt(JOptionPane.showInputDialog(this, ">> Ingrese el numero de Columnas:"));
        int answer1 = 0;
        JOptionPane.showMessageDialog(this, "La Matriz en RowProduct en (" + filaEsp + "," + columnaEsp+") es: \n" + rowProduct(matrix2, matrix3, filaEsp, columnaEsp, 1, answer1));
        JOptionPane.showMessageDialog(this, "La Matriz en Multiplicada es: \n" + Print(multiplicacion(matrix2, matrix3, matrix, fila, columna), fila, columna,answer2));
        
    }//GEN-LAST:event_Tesla1MouseClicked

    private void Tesla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tesla1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tesla1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recursion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recursion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recursion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recursion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recursion().setVisible(true);
            }
        });
    }

    public static int[][] lectura(int[][] matrix, int fila, int columna) {
        if (fila < matrix.length) {
            System.out.println("FORTIN GAYYYYY0");
            if (columna < matrix[0].length) {
                System.out.println("FORTIN GAYYYYY");
                matrix[fila][columna] = aleatorio.nextInt(10);
                return lectura(matrix, fila, columna + 1);
            }
            System.out.println("FORTIN GAYYYYY2");
            return lectura(matrix, fila + 1, 0);
        }
        return matrix;
    }

    public static String Print(int[][] matrix, int fila, int columna, String resp) {
        if (fila >= 0 && columna >= 0) {
            resp = '[' + Integer.toString(matrix[fila][columna]) + ']' + resp;
        }

        if (fila == 0 && columna == 0) {
            System.out.println("fortin");
            return resp;
        } else {
            if (columna == 0) {
                System.out.println("es");
                resp = '\n' + resp;
                return Print(matrix, fila - 1, matrix[0].length - 1, resp);
            } else {
                System.out.println("gay");
                return Print(matrix, fila, columna - 1, resp);
            }
        }
    }

    public static int rowProduct(int[][] Matrix1, int[][] Matrix2, int i, int j, int k, int answer) {
        if (k < Matrix1[0].length) {
            return rowProduct (Matrix1,Matrix2,i, j, k+1,answer +(Matrix1[i][k]*Matrix2[k][j]));
        }
        return answer;
    }
    
    public static int [][] multiplicacion(int [][] Matrix1, int [][] Matrix2, int [][] Matrix3, int i, int j){
        if (i < Matrix1.length){
            if (j < Matrix2[0].length){
                Matrix3 [i][j] = rowProduct(Matrix1, Matrix2, i, j,0,0);
                return multiplicacion(Matrix1, Matrix2, Matrix3, i, j+1);
            }
            return multiplicacion(Matrix1, Matrix2, Matrix3, i, 0);
        }
        return Matrix3;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Personas;
    private javax.swing.JButton Tesla;
    private javax.swing.JButton Tesla1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
